# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/jh/code/QtDemo/Project_Github/ChatProject/client_Trial/untitled_test_basic.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1000, 600))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.chatTab = QtWidgets.QWidget()
        self.chatTab.setObjectName("chatTab")
        self.widget_3 = QtWidgets.QWidget(self.chatTab)
        self.widget_3.setGeometry(QtCore.QRect(0, 0, 841, 561))
        self.widget_3.setObjectName("widget_3")
        self.chatMsgList = QtWidgets.QListWidget(self.widget_3)
        self.chatMsgList.setGeometry(QtCore.QRect(0, 0, 274, 550))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chatMsgList.sizePolicy().hasHeightForWidth())
        self.chatMsgList.setSizePolicy(sizePolicy)
        self.chatMsgList.setMinimumSize(QtCore.QSize(100, 75))
        self.chatMsgList.setObjectName("chatMsgList")
        self.showMsgPage = QtWidgets.QGroupBox(self.widget_3)
        self.showMsgPage.setGeometry(QtCore.QRect(274, 0, 621, 550))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showMsgPage.sizePolicy().hasHeightForWidth())
        self.showMsgPage.setSizePolicy(sizePolicy)
        self.showMsgPage.setMinimumSize(QtCore.QSize(200, 150))
        self.showMsgPage.setObjectName("showMsgPage")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.showMsgPage)
        self.horizontalLayout_4.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget = QtWidgets.QWidget(self.showMsgPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.chatFuncList = QtWidgets.QListWidget(self.widget)
        self.chatFuncList.setGeometry(QtCore.QRect(0, 350, 631, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.chatFuncList.sizePolicy().hasHeightForWidth())
        self.chatFuncList.setSizePolicy(sizePolicy)
        self.chatFuncList.setFlow(QtWidgets.QListView.LeftToRight)
        self.chatFuncList.setObjectName("chatFuncList")
        self.chatMsgEdit = QtWidgets.QTextEdit(self.widget)
        self.chatMsgEdit.setGeometry(QtCore.QRect(0, 374, 631, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.chatMsgEdit.sizePolicy().hasHeightForWidth())
        self.chatMsgEdit.setSizePolicy(sizePolicy)
        self.chatMsgEdit.setObjectName("chatMsgEdit")
        self.chatSendBtn = QtWidgets.QPushButton(self.widget)
        self.chatSendBtn.setGeometry(QtCore.QRect(450, 440, 97, 32))
        self.chatSendBtn.setObjectName("chatSendBtn")
        self.chatMsgBrowser = QtWidgets.QScrollArea(self.widget)
        self.chatMsgBrowser.setGeometry(QtCore.QRect(0, 0, 551, 321))
        self.chatMsgBrowser.setWidgetResizable(True)
        self.chatMsgBrowser.setObjectName("chatMsgBrowser")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 549, 319))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.chatMsgBrowser.setWidget(self.scrollAreaWidgetContents)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(10, 350, 50, 32))
        self.pushButton.setObjectName("pushButton")
        self.sendFileBtn = QtWidgets.QPushButton(self.widget)
        self.sendFileBtn.setGeometry(QtCore.QRect(80, 350, 97, 32))
        self.sendFileBtn.setObjectName("sendFileBtn")
        self.chatMsgEdit.raise_()
        self.chatFuncList.raise_()
        self.chatSendBtn.raise_()
        self.chatMsgBrowser.raise_()
        self.pushButton.raise_()
        self.sendFileBtn.raise_()
        self.horizontalLayout_4.addWidget(self.widget)
        self.tabWidget.addTab(self.chatTab, "")
        self.contactTab = QtWidgets.QWidget()
        self.contactTab.setObjectName("contactTab")
        self.contactSearchEdit = QtWidgets.QLineEdit(self.contactTab)
        self.contactSearchEdit.setGeometry(QtCore.QRect(8, 12, 201, 31))
        self.contactSearchEdit.setObjectName("contactSearchEdit")
        self.searchAccountBtn = QtWidgets.QPushButton(self.contactTab)
        self.searchAccountBtn.setGeometry(QtCore.QRect(213, 11, 21, 32))
        self.searchAccountBtn.setObjectName("searchAccountBtn")
        self.contactListStack = QtWidgets.QStackedWidget(self.contactTab)
        self.contactListStack.setGeometry(QtCore.QRect(0, 50, 274, 491))
        self.contactListStack.setObjectName("contactListStack")
        self.contactFriendPage = QtWidgets.QWidget()
        self.contactFriendPage.setObjectName("contactFriendPage")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.contactFriendPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.manageContactsBtn = QtWidgets.QPushButton(self.contactFriendPage)
        self.manageContactsBtn.setObjectName("manageContactsBtn")
        self.verticalLayout.addWidget(self.manageContactsBtn)
        self.contactsList = QtWidgets.QTreeWidget(self.contactFriendPage)
        self.contactsList.setObjectName("contactsList")
        item_0 = QtWidgets.QTreeWidgetItem(self.contactsList)
        item_0 = QtWidgets.QTreeWidgetItem(self.contactsList)
        self.verticalLayout.addWidget(self.contactsList)
        self.contactListStack.addWidget(self.contactFriendPage)
        self.addFriendPage = QtWidgets.QWidget()
        self.addFriendPage.setObjectName("addFriendPage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.addFriendPage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.addContactList = QtWidgets.QTreeWidget(self.addFriendPage)
        self.addContactList.setObjectName("addContactList")
        item_0 = QtWidgets.QTreeWidgetItem(self.addContactList)
        item_0 = QtWidgets.QTreeWidgetItem(self.addContactList)
        self.verticalLayout_2.addWidget(self.addContactList)
        self.contactListStack.addWidget(self.addFriendPage)
        self.addAccountBtn = QtWidgets.QPushButton(self.contactTab)
        self.addAccountBtn.setGeometry(QtCore.QRect(240, 11, 21, 32))
        self.addAccountBtn.setObjectName("addAccountBtn")
        self.showContactPage = QtWidgets.QGroupBox(self.contactTab)
        self.showContactPage.setGeometry(QtCore.QRect(274, 0, 621, 550))
        self.showContactPage.setObjectName("showContactPage")
        self.pushButton_2 = QtWidgets.QPushButton(self.showContactPage)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 160, 97, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tabWidget.addTab(self.contactTab, "")
        self.groupChatTab = QtWidgets.QWidget()
        self.groupChatTab.setObjectName("groupChatTab")
        self.tabWidget.addTab(self.groupChatTab, "")
        self.groupContactTab = QtWidgets.QWidget()
        self.groupContactTab.setObjectName("groupContactTab")
        self.contactSearchEdit_2 = QtWidgets.QLineEdit(self.groupContactTab)
        self.contactSearchEdit_2.setGeometry(QtCore.QRect(8, 13, 201, 31))
        self.contactSearchEdit_2.setObjectName("contactSearchEdit_2")
        self.searchAccountBtn_2 = QtWidgets.QPushButton(self.groupContactTab)
        self.searchAccountBtn_2.setGeometry(QtCore.QRect(213, 12, 21, 32))
        self.searchAccountBtn_2.setObjectName("searchAccountBtn_2")
        self.addAccountBtn_2 = QtWidgets.QPushButton(self.groupContactTab)
        self.addAccountBtn_2.setGeometry(QtCore.QRect(240, 12, 21, 32))
        self.addAccountBtn_2.setObjectName("addAccountBtn_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.groupContactTab)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 50, 274, 491))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.manageContactsBtn_2 = QtWidgets.QPushButton(self.page)
        self.manageContactsBtn_2.setObjectName("manageContactsBtn_2")
        self.verticalLayout_3.addWidget(self.manageContactsBtn_2)
        self.contactFriendList_2 = QtWidgets.QListWidget(self.page)
        self.contactFriendList_2.setObjectName("contactFriendList_2")
        self.verticalLayout_3.addWidget(self.contactFriendList_2)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.tabWidget.addTab(self.groupContactTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 29))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.contactListStack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.chatMsgList.setSortingEnabled(True)
        self.showMsgPage.setTitle(_translate("MainWindow", "Contact Name"))
        self.chatSendBtn.setText(_translate("MainWindow", "send"))
        self.pushButton.setText(_translate("MainWindow", "表情"))
        self.sendFileBtn.setText(_translate("MainWindow", "发送文件"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.chatTab), _translate("MainWindow", "Chat"))
        self.contactSearchEdit.setPlaceholderText(_translate("MainWindow", "用户名/id 搜索好友"))
        self.searchAccountBtn.setText(_translate("MainWindow", "search"))
        self.manageContactsBtn.setText(_translate("MainWindow", "ManageContacts"))
        self.contactsList.headerItem().setText(0, _translate("MainWindow", "Contacts"))
        __sortingEnabled = self.contactsList.isSortingEnabled()
        self.contactsList.setSortingEnabled(False)
        self.contactsList.topLevelItem(0).setText(0, _translate("MainWindow", "联系人"))
        self.contactsList.topLevelItem(1).setText(0, _translate("MainWindow", "群聊天"))
        self.contactsList.setSortingEnabled(__sortingEnabled)
        self.addContactList.headerItem().setText(0, _translate("MainWindow", "ADD Contacts/Group"))
        __sortingEnabled = self.addContactList.isSortingEnabled()
        self.addContactList.setSortingEnabled(False)
        self.addContactList.topLevelItem(0).setText(0, _translate("MainWindow", "联系人"))
        self.addContactList.topLevelItem(1).setText(0, _translate("MainWindow", "群聊天"))
        self.addContactList.setSortingEnabled(__sortingEnabled)
        self.addAccountBtn.setText(_translate("MainWindow", "PushButton"))
        self.showContactPage.setTitle(_translate("MainWindow", "Contact Info"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.contactTab), _translate("MainWindow", "Contact"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.groupChatTab), _translate("MainWindow", "页"))
        self.contactSearchEdit_2.setPlaceholderText(_translate("MainWindow", "用户名/id 搜索好友"))
        self.searchAccountBtn_2.setText(_translate("MainWindow", "search"))
        self.addAccountBtn_2.setText(_translate("MainWindow", "PushButton"))
        self.manageContactsBtn_2.setText(_translate("MainWindow", "ManageContacts"))
        self.contactFriendList_2.setSortingEnabled(True)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.groupContactTab), _translate("MainWindow", "addFriend"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))


