# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/jh/code/QtDemo/Project/untitled_test_basic.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1000, 600))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.chatTab = QtWidgets.QWidget()
        self.chatTab.setObjectName("chatTab")
        self.widget_3 = QtWidgets.QWidget(self.chatTab)
        self.widget_3.setGeometry(QtCore.QRect(0, 0, 841, 561))
        self.widget_3.setObjectName("widget_3")
        self.listWidget_4 = QtWidgets.QListWidget(self.widget_3)
        self.listWidget_4.setGeometry(QtCore.QRect(0, 0, 161, 550))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_4.sizePolicy().hasHeightForWidth())
        self.listWidget_4.setSizePolicy(sizePolicy)
        self.listWidget_4.setMinimumSize(QtCore.QSize(100, 75))
        self.listWidget_4.setObjectName("listWidget_4")
        self.groupBox = QtWidgets.QGroupBox(self.widget_3)
        self.groupBox.setGeometry(QtCore.QRect(161, 0, 761, 550))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(200, 150))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget = QtWidgets.QWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.chatTextBrowser = QtWidgets.QTextBrowser(self.widget)
        self.chatTextBrowser.setGeometry(QtCore.QRect(0, 0, 631, 351))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(80)
        sizePolicy.setHeightForWidth(self.chatTextBrowser.sizePolicy().hasHeightForWidth())
        self.chatTextBrowser.setSizePolicy(sizePolicy)
        self.chatTextBrowser.setObjectName("chatTextBrowser")
        self.chatFuncList = QtWidgets.QListView(self.widget)
        self.chatFuncList.setGeometry(QtCore.QRect(0, 350, 631, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.chatFuncList.sizePolicy().hasHeightForWidth())
        self.chatFuncList.setSizePolicy(sizePolicy)
        self.chatFuncList.setObjectName("chatFuncList")
        self.chatMsgEdit = QtWidgets.QTextEdit(self.widget)
        self.chatMsgEdit.setGeometry(QtCore.QRect(0, 374, 631, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.chatMsgEdit.sizePolicy().hasHeightForWidth())
        self.chatMsgEdit.setSizePolicy(sizePolicy)
        self.chatMsgEdit.setObjectName("chatMsgEdit")
        self.chatSendBtn = QtWidgets.QPushButton(self.widget)
        self.chatSendBtn.setGeometry(QtCore.QRect(520, 460, 97, 32))
        self.chatSendBtn.setObjectName("chatSendBtn")
        self.chatMsgEdit.raise_()
        self.chatTextBrowser.raise_()
        self.chatFuncList.raise_()
        self.chatSendBtn.raise_()
        self.horizontalLayout_4.addWidget(self.widget)
        self.tabWidget.addTab(self.chatTab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.contactFriendList = QtWidgets.QListWidget(self.tab_3)
        self.contactFriendList.setGeometry(QtCore.QRect(0, 0, 161, 550))
        self.contactFriendList.setObjectName("contactFriendList")
        item = QtWidgets.QListWidgetItem()
        self.contactFriendList.addItem(item)
        self.tabWidget.addTab(self.tab_3, "")
        self.contactTab = QtWidgets.QWidget()
        self.contactTab.setObjectName("contactTab")
        self.listWidget_3 = QtWidgets.QListWidget(self.contactTab)
        self.listWidget_3.setGeometry(QtCore.QRect(0, 0, 161, 550))
        self.listWidget_3.setObjectName("listWidget_3")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        self.tabWidget.addTab(self.contactTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 29))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.listWidget_4.setSortingEnabled(True)
        self.groupBox.setTitle(_translate("MainWindow", "Contract Name"))
        self.chatSendBtn.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.chatTab), _translate("MainWindow", "Chat"))
        self.contactFriendList.setSortingEnabled(True)
        __sortingEnabled = self.contactFriendList.isSortingEnabled()
        self.contactFriendList.setSortingEnabled(False)
        item = self.contactFriendList.item(0)
        item.setText(_translate("MainWindow", "新建项目"))
        self.contactFriendList.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Contact"))
        self.listWidget_3.setSortingEnabled(True)
        __sortingEnabled = self.listWidget_3.isSortingEnabled()
        self.listWidget_3.setSortingEnabled(False)
        item = self.listWidget_3.item(0)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget_3.item(1)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget_3.item(2)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget_3.item(3)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget_3.item(4)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget_3.item(5)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget_3.item(6)
        item.setText(_translate("MainWindow", "新建项目"))
        self.listWidget_3.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.contactTab), _translate("MainWindow", "addFriend"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))


