# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logindialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.setEnabled(True)
        LoginDialog.resize(651, 651)
        LoginDialog.setAcceptDrops(False)
        LoginDialog.setAccessibleDescription("")
        self.label = QtWidgets.QLabel(LoginDialog)
        self.label.setGeometry(QtCore.QRect(60, 290, 81, 24))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK SC")
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pwdLineEdit = QtWidgets.QLineEdit(LoginDialog)
        self.pwdLineEdit.setGeometry(QtCore.QRect(170, 420, 321, 32))
        self.pwdLineEdit.setText("")
        self.pwdLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwdLineEdit.setObjectName("pwdLineEdit")
        self.exitBtn = QtWidgets.QPushButton(LoginDialog)
        self.exitBtn.setGeometry(QtCore.QRect(450, 530, 97, 32))
        self.exitBtn.setObjectName("exitBtn")
        self.label_2 = QtWidgets.QLabel(LoginDialog)
        self.label_2.setGeometry(QtCore.QRect(60, 420, 72, 24))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK SC")
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.loginBtn = QtWidgets.QPushButton(LoginDialog)
        self.loginBtn.setGeometry(QtCore.QRect(80, 530, 97, 32))
        self.loginBtn.setAutoDefault(True)
        self.loginBtn.setObjectName("loginBtn")
        self.usrLineEdit = QtWidgets.QLineEdit(LoginDialog)
        self.usrLineEdit.setGeometry(QtCore.QRect(170, 290, 321, 32))
        self.usrLineEdit.setObjectName("usrLineEdit")
        self.registerBtn = QtWidgets.QPushButton(LoginDialog)
        self.registerBtn.setGeometry(QtCore.QRect(260, 530, 91, 31))
        self.registerBtn.setObjectName("registerBtn")
        self.faceBtn = QtWidgets.QPushButton(LoginDialog)
        self.faceBtn.setEnabled(True)
        self.faceBtn.setGeometry(QtCore.QRect(510, 420, 89, 31))
        self.faceBtn.setObjectName("faceBtn")
        self.label_3 = QtWidgets.QLabel(LoginDialog)
        self.label_3.setGeometry(QtCore.QRect(100, 100, 441, 101))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "Dialog"))
        self.label.setText(_translate("LoginDialog", "UserName"))
        self.pwdLineEdit.setPlaceholderText(_translate("LoginDialog", "请输入密码"))
        self.exitBtn.setText(_translate("LoginDialog", ""))
        self.label_2.setText(_translate("LoginDialog", "Password"))
        self.loginBtn.setText(_translate("LoginDialog", ""))
        self.usrLineEdit.setPlaceholderText(_translate("LoginDialog", "请输入用户名"))
        self.registerBtn.setText(_translate("LoginDialog", ""))
        self.faceBtn.setText(_translate("LoginDialog", ""))
        self.label_3.setText(_translate("LoginDialog", "TITLE"))
