# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logindialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import PyQt5
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon

class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(400, 300)
        self.label = QtWidgets.QLabel(LoginDialog)
        self.label.setGeometry(QtCore.QRect(50, 70, 67, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(LoginDialog)
        self.label_2.setGeometry(QtCore.QRect(50, 130, 67, 17))
        self.label_2.setObjectName("label_2")
        self.usrLineEdit = QtWidgets.QLineEdit(LoginDialog)
        self.usrLineEdit.setGeometry(QtCore.QRect(180, 70, 113, 25))
        self.usrLineEdit.setObjectName("usrLineEdit")
        self.pwdLineEdit = QtWidgets.QLineEdit(LoginDialog)
        self.pwdLineEdit.setGeometry(QtCore.QRect(180, 130, 113, 25))
        self.pwdLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwdLineEdit.setObjectName("pwdLineEdit")
        self.loginBtn = QtWidgets.QPushButton(LoginDialog)
        self.loginBtn.setGeometry(QtCore.QRect(50, 190, 89, 25))
        self.loginBtn.setObjectName("loginBtn")
        self.exitBtn = QtWidgets.QPushButton(LoginDialog)
        self.exitBtn.setGeometry(QtCore.QRect(200, 190, 89, 25))
        self.exitBtn.setObjectName("exitBtn")
        self.retranslateUi(LoginDialog)
        self.exitBtn.clicked.connect(LoginDialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "Dialog"))
        self.label.setText(_translate("LoginDialog", "User"))
        self.label_2.setText(_translate("LoginDialog", "Password"))
        self.usrLineEdit.setPlaceholderText(_translate("LoginDialog", "用户名"))
        self.usrLineEdit.setStyleSheet("QLineEdit{font-size:13px; background:transparent; border:none; border-bottom:1px solid rgb(229, 229, 229);}"
                                        "QLineEdit:hover{border-bottom:1px solid rgb(193,193, 193);}"
                                        "QLineEdit:focus{border-bottom:1px solid rgb(18, 183, 245);}"
                                       )
        self.pwdLineEdit.setPlaceholderText(_translate("LoginDialog", "密码"))
        self.pwdLineEdit.setStyleSheet("QLineEdit{font-size:13px; background:transparent; border:none; border-bottom:1px solid rgb(229, 229, 229);}"
                                        "QLineEdit:hover{border-bottom:1px solid rgb(193,193, 193);}"
                                        "QLineEdit:focus{border-bottom:1px solid rgb(18, 183, 245);}"
                                       )
        self.loginBtn.setText(_translate("LoginDialog", "Login"))
        self.loginBtn.setIcon(QIcon("./picture/login.png"))
        self.loginBtn.setStyleSheet("QPushButton{background:#FFFF00;border-radius:10px}" #设置按钮颜色以及边框圆角化
                                   "QPushButton:hover{background:#00FFFF}" #悬挂时颜色
                                   )
        self.exitBtn.setText(_translate("LoginDialog", "Exit"))
        self.exitBtn.setIcon(QIcon("./picture/exit.png"))
        self.exitBtn.setStyleSheet("QPushButton{background:#00FFFF;border-radius:10px}" 
                                    "QPushButton:hover{background:#FF0000}"
                                    )