# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logindialog1.0.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import PyQt5
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon

class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(651, 309)
        self.label = QtWidgets.QLabel(LoginDialog)
        self.label.setGeometry(QtCore.QRect(70, 100, 81, 24))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK SC")
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pwdLineEdit = QtWidgets.QLineEdit(LoginDialog)
        self.pwdLineEdit.setGeometry(QtCore.QRect(180, 150, 321, 32))
        self.pwdLineEdit.setText("")
        self.pwdLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwdLineEdit.setObjectName("pwdLineEdit")
        self.exitBtn = QtWidgets.QPushButton(LoginDialog)
        self.exitBtn.setGeometry(QtCore.QRect(250, 260, 97, 32))
        self.exitBtn.setObjectName("exitBtn")
        self.exitBtn.setIcon(QIcon("./picture/exit.png"))
        self.label_2 = QtWidgets.QLabel(LoginDialog)
        self.label_2.setGeometry(QtCore.QRect(70, 150, 72, 24))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK SC")
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.loginBtn = QtWidgets.QPushButton(LoginDialog)
        self.loginBtn.setGeometry(QtCore.QRect(250, 220, 97, 32))
        self.loginBtn.setObjectName("loginBtn")
        self.loginBtn.setIcon(QIcon("./picture/login.png"))
        self.usrLineEdit = QtWidgets.QLineEdit(LoginDialog)
        self.usrLineEdit.setGeometry(QtCore.QRect(180, 100, 321, 32))
        self.usrLineEdit.setObjectName("usrLineEdit")

        self.retranslateUi(LoginDialog)
        self.exitBtn.clicked.connect(LoginDialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "Dialog"))
        self.label.setText(_translate("LoginDialog", "UserName"))
        self.pwdLineEdit.setPlaceholderText(_translate("LoginDialog", "请输入密码"))
        self.pwdLineEdit.setStyleSheet(
            "QLineEdit{font-size:13px; background:transparent; border:none; border-bottom:1px solid rgb(229, 229, 229);}"
            "QLineEdit:hover{border-bottom:1px solid rgb(193,193, 193);}"
            "QLineEdit:focus{border-bottom:1px solid rgb(18, 183, 245);}"
            )
        self.exitBtn.setText(_translate("LoginDialog", "Exit"))
        self.exitBtn.setStyleSheet("QPushButton{background:#00FFFF;border-radius:10px}"
                                   "QPushButton:hover{background:#FF0000}"
                                   )
        self.label_2.setText(_translate("LoginDialog", "Password"))
        self.loginBtn.setText(_translate("LoginDialog", "Login"))
        self.loginBtn.setStyleSheet("QPushButton{background:#FFFF00;border-radius:10px}"  # 设置按钮颜色以及边框圆角化
                                    "QPushButton:hover{background:#00FFFF}"  # 悬挂时颜色
                                    )
        self.usrLineEdit.setPlaceholderText(_translate("LoginDialog", "请输入用户名"))
        self.usrLineEdit.setStyleSheet(
            "QLineEdit{font-size:13px; background:transparent; border:none; border-bottom:1px solid rgb(229, 229, 229);}"
            "QLineEdit:hover{border-bottom:1px solid rgb(193,193, 193);}"
            "QLineEdit:focus{border-bottom:1px solid rgb(18, 183, 245);}"
            )