# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'png.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Png(object):
    def setupUi(self, Png):
        Png.setObjectName("Png")
        Png.resize(400, 300)
        self.png = QtWidgets.QLabel(Png)
        self.png.setGeometry(QtCore.QRect(160, 120, 67, 67))
        self.png.setObjectName("png")

        self.retranslateUi(Png)
        QtCore.QMetaObject.connectSlotsByName(Png)

    def retranslateUi(self, Png):
        _translate = QtCore.QCoreApplication.translate
        Png.setWindowTitle(_translate("Png", "Dialog"))
        self.png.setText(_translate("Png", "TextLabel"))
